### PR TITLE
Fix Microchip SAM D21/DA1 default interrupt vector table linking

### LINKED ISSUE #75: Fix Microchip SAM D21/DA1 default interrupt vector table linking
Fix Microchip SAM D21/DA1 default interrupt vector table linking.
- [x] Move the default vector table instance and associated interrupt handler functions to the `include/picolibrary/microchip/sam/d21da1/interrupt/default_vector_table.h`/`source/picolibrary/microchip/sam/d21da1/interrupt/default_vector_table.cc` header/source file pair
- [x] Add `picolibrary-microchip-sam-d21da1-interrupt-default_vector_table` object library
- [x] Documentation
    - [x] `docs/usage.md`
    - [x] `docs/interrupt.md`

The default vector table is currently part of a static library which results in it not being added to an executable that links with the static library since nothing in the application references the default vector table.

### PR DESCRIPTION
**Pull request by apcountryman**
Resolves #75 (Fix Microchip SAM D21/DA1 default interrupt vector table linking).

The default interrupt vector table instance was part of a static library which resulted in it not being added to executables that link with the static library since nothing in the executables references the default interrupt vector table instance.

This pull request:
- [x] Implements a bug fix
- [ ] Implements an enhancement to an existing feature
- [ ] Implements a new feature
- [ ] Performs a refactoring

Please mark the pull request as "Ready for review" and request a review when the pull
request is ready for a review.
If changes are requested, please discuss and/or address the review findings before
requesting a new review.

@apcountryman

### CODE REVIEW

File: source/picolibrary/microchip/sam/d21da1/interrupt/default_vector_table.cc [hunk 1]
```diff
@@ -0,0 +1,233 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software distributed under
+ * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+ * KIND, either express or implied. See the License for the specific language governing
+ * permissions and limitations under the License.
+ */
+
+/**
+ * \file
+ * \brief picolibrary::Microchip::SAM::D21DA1::Interrupt implementation.
```
Comment (apcountryman) [inline source/picolibrary/microchip/sam/d21da1/interrupt/default_vector_table.cc]:
```suggestion
 * \brief picolibrary::Microchip::SAM::D21DA1::Interrupt default vector table
 *        implementation.
```

**Review by apcountryman — COMMENTED** [review]
No review findings.
